"""Initial schema

Revision ID: 185b53538f50
Revises: 
Create Date: 2026-07-04 19:29:48.982381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '185b53538f50'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime',
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('episodes', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('members', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('anime_id')
    )
    op.create_table('genre',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('genre_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('genre_id'),
    sa.UniqueConstraint('genre_name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('anime_genre',
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.anime_id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.genre_id'], ),
    sa.PrimaryKeyConstraint('anime_id', 'genre_id')
    )
    op.create_table('dataset_ratings',
    sa.Column('dataset_rating_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_user_id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.anime_id'], ),
    sa.PrimaryKeyConstraint('dataset_rating_id')
    )
    op.create_index(op.f('ix_dataset_ratings_dataset_user_id'), 'dataset_ratings', ['dataset_user_id'], unique=False)
    op.create_table('favorites',
    sa.Column('favorite_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.anime_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('favorite_id'),
    sa.UniqueConstraint('user_id', 'anime_id', name='uq_user_favorite')
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.anime_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('user_ratings',
    sa.Column('user_rating_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('rated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.anime_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_rating_id'),
    sa.UniqueConstraint('user_id', 'anime_id', name='uq_user_anime_rating')
    )
    op.create_table('watchlists',
    sa.Column('watchlist_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.anime_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('watchlist_id'),
    sa.UniqueConstraint('user_id', 'anime_id', name='uq_user_watchlist')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlists')
    op.drop_table('user_ratings')
    op.drop_table('reviews')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_dataset_ratings_dataset_user_id'), table_name='dataset_ratings')
    op.drop_table('dataset_ratings')
    op.drop_table('anime_genre')
    op.drop_table('users')
    op.drop_table('genre')
    op.drop_table('anime')
    # ### end Alembic commands ###
