"""add poster_url to anime

Revision ID: fbd631b0063b
Revises: 185b53538f50
Create Date: 2026-07-06 00:17:09.389734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbd631b0063b'
down_revision: Union[str, Sequence[str], None] = '185b53538f50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime', sa.Column('poster_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anime', 'poster_url')
    # ### end Alembic commands ###
